config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create, :update]

  resources :wikis do
    resources :comments, only: [:create, :destroy]
    resources :collaborators, only: [:create]
  end

  devise_for :users, controllers: {registrations: "registrations"}

  resources :users, only: [:show]

  root to: 'wikis#index'
end

app/models/wiki.rb
# == Schema Information
#
# Table name: wikis
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  private    :boolean          default(FALSE)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :comments, dependent: :destroy

  extend FriendlyId
  friendly_id :title, use: :slugged

  def private?
    private == false
  end

  scope :visible_to, -> (user) {
    if !user
      []
    elsif user.role == 'standard'
      where(private: false)
    elsif user.role == 'premium'
      all
    end
  }
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    @collaborator = Collaborator.new
    @comments = @wiki.comments
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    if @wiki.save
      flash[:notice] = "Wiki was saved"
      redirect_to @wiki
    else
      flash[:error] = "Too bad"
      render :new
    end
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "Another error."
      render :edit
    end
  end

  def destroy

    @wiki = Wiki.friendly.find(params[:id])

    if @wiki.destroy
      @wikis = policy_scope(Wiki)
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to(:back)
    else
      @wikis = policy_scope(Wiki)
      flash[:error] = "There seems to be a problem."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_collab_form.html.erb
<h3>Add Collaborators</h3>
  <%= form_for [@wiki, @collaborator] do |f| %>
    <% if @collaborator.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(@collaborator.errors.count, "error") %>.</h4>
       <ul>
         <% @collaborator.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
     <% elsif @collaborator.save %>
      <div class="alert alert-success">
        <h4>Your Collaborator has been added.</h4>
      </div>
    <% end %>

    <%= form_group_tag(@collaborator.errors[:email]) do %>
      <% f.label "email" %>
      <%= text_field_tag "email", nil, class: 'form-control', placeholder: "Collaborator's email" %>
    <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>

app/views/wikis/_wiki.html.erb
<%= content_tag :tr, id: "wiki-#{wiki.id}" do %>
  <td><%= link_to wiki.title, wiki_path(wiki.id) %></td>
  <td>
    <small>
      submitted <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.name %>
    </small>
  </td>

    <% if current_user && current_user.role == "premium" %>
      <td><%= link_to "Edit", edit_wiki_path(wiki), class: 'btn btn-success btn-sm inline clear-right' %></td>
      <td><%= link_to "Delete", wiki, method: :delete, class: 'btn btn-danger btn-sm' %></td>
    <% end %>
<% end %>

app/views/wikis/edit.html.erb
<div class="container">
  <h1>Edit Wiki</h1>

  <div class="row">
    <div class="col-md-4">
      <p>Guidlines for Wiki</p>
      <ul>
        <li>Keep the Wiki clean and informative</li>
        <li>Add usefull information</li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= form_for @wiki do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Enter your Wiki title" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter your info" %>
        </div>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/index.html.erb
<br>
<div class="jumbotron">
  <div class="container">
    <h1>Blocipedia</h1>
    <p>Blocipedia is a great way to share information!</p>
    <p>
      <% if current_user %>
        Hello <%= current_user.name %><br>
        <% if current_user.role == "premium" %>
          <%= link_to "Downgrade Account", charge_path(current_user), class: "btn btn-danger btn-sm", method: :patch, :onclick => "alert('Downgrade collected!')" %>
        <% else %>
          <%= link_to "Upgrade", new_charge_path, class: "btn btn-success btn-sm" %>
        <% end %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
      <% end %>
    </p>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>Create a new Wiki topic</h2>
      <p><%= link_to "Create", new_wiki_path, class: 'btn btn-primary' %></p>
    </div>
    <% if current_user %>
      <div class="col-md-6">
        <h2>Active Wiki's</h2
          <div class="media">
            <div class="media-body">
              <table class="table table-striped">
                <tbody>
                  <%= render partial: 'wiki', collection: @wikis %>
                </tbody>
              </table>
            </div>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/new.html.erb
<div class="container">
  <h1>New Wiki</h1>

  <div class="row">
    <div class="col-md-4">
      <p>Guidlines for Wiki</p>
      <ul>
        <li>Keep the Wiki clean and informative</li>
        <li>Add usefull information</li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= form_for @wiki do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Enter your Wiki title" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter your info" %>
        </div>
        <% if current_user.role == 'admin' || current_user.role == 'premium' %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' %>
            <%= f.check_box :private %> Private wiki
          </div>
        <% end %>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/show.html.erb
<div class="container">
  <h1><%= markdown_to_html @wiki.title %></h1>
  <% if policy(@wiki).edit? || @wiki.user.id == current_user.id %>
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger' %>
  <% end %>
  <p><%= markdown_to_html @wiki.body %></p>
  <h4>Comments</h4>
    <div class="media">
      <div class="media-body">
        <table class="table table-striped">
          <tbody class="comment-table">
            <%= render partial: 'comments/comment', collection: @comments %>
        </tbody>
      </table>
    </div>
  </div>
  </div>
  <% array = [] %>
  <% @wiki.collaborators.each do |collaborator| %>
    <% u_id = collaborator.user_id %>
    <% array << u_id %>
  <% end %>
  <% if @wiki.collaborators.count > 0 %>
  <div style="background-color: #EFF0F1; padding: 15px 0px; color: green;">
    <div class="container">
      <h4>Current Collaborators</h4>
      <% @wiki.collaborators.each do |collab| %>
        <span><%= collab.user.name %> | </span>
      <% end %>
    </div>
  </div>
  <% else %>
  <div class="container">
    <div class="list-group">
      <h4 class="list-group-item active">Be the first to collaborate</h4>
    </div>
  </div>
  <% end %>
  <% if current_user.admin? || array.include?(current_user.id) %>
  <div class="row">
    <div style="background-color: #EFF0F1; padding-top: 50px; padding-bottom: 20px; box-shadow: inset 0px 10px 10px #888888;">
      <div class="container">
        <div class="col-md-6">
          <%= render partial: 'comments/form' %>
        </div>
        <div class="col-md-6">
          <%= render partial: "collab_form" %>
        </div>
      </div>
    </div>
  </div>
  <% else %>
    <div class="container">
      <%= render partial: "wikis/collab_form" %>
    </div>
  <% end %>